### ISSUE TITLE
OSM sürekli çizgi araç bileşeninin başlangıç ve bitiş aramalarina göre güncellenmesi.

### ISSUE THREAD

**Issue by farunurisonmez** [farunurisonmez/client-app-osrm#14]

**Comment by 0xfaru** [comment]
<img width="1440" alt="Screenshot 2023-12-14 at 16 37 54" src="https://github.com/farunurisonmez/osrm-client-app/assets/23061257/0395b757-7cf8-459a-8e2b-464099e23faa">
<img width="1291" alt="Screenshot 2023-12-14 at 16 38 40" src="https://github.com/farunurisonmez/osrm-client-app/assets/23061257/a623d5e8-c488-42ab-96ac-906a5e5e86b2">
<img width="1440" alt="Screenshot 2023-12-14 at 16 39 21" src="https://github.com/farunurisonmez/osrm-client-app/assets/23061257/b30738d1-eb6f-42cf-b7ea-50489c349270">
