### ISSUE TITLE
OSM sürekli çizgi araç bileşeni geliştirmesi

### ISSUE THREAD

**Issue by farunurisonmez** [farunurisonmez/client-app-osrm#8]
Bu görev, OpenStreetMap (OSM) Poliline Tool bileşenini geliştirmeyi içerir. Bu bileşen, verilen iki koordinat arasındaki rota bilgilerini alır ve bu rotanın üzerinde belirtilen renkte ve kalınlıkta bir çizgi çizer. Görev, bu bileşenin aşağıdaki özelliklerini içerir:

İki nokta arasındaki rota bilgisini alacak bir servis entegrasyonu: Kod, verilen başlangıç ve bitiş koordinatları için OSRM servisini kullanarak rota bilgilerini alır. Bu rotanın detaylarını alır ve kullanılabilir hale getirir.
Rota üzerindeki kesişim noktalarının çizimi: Kesişim noktaları ve bu noktalardan oluşturulan rota hattı, haritada açıkça gösterilmelidir.
Harita üzerinde odaklanma: Harita, rota hattını net bir şekilde görüntülemek için ilgili bölgelerde odaklanmalıdır.
Renk ve kalınlık seçeneği: Çizgi rengi ve kalınlığı, bileşenin kullanıcı tarafından ayarlanabilir olmalıdır. Örnek olarak, çizgiyi mavi renkte ve 10 piksel kalınlığında çizebilmeliyiz.

**Comment by 0xfaru** [comment]
<img width="1427" alt="Screenshot 2023-10-22 at 20 56 33" src="https://github.com/farunurisonmez/client-app-osrm/assets/23061257/20035a07-f667-4371-afc8-6cfc3900ee83">
