### ISSUE TITLE
GitHub sayfa yayınlama işlemi

### ISSUE THREAD

**Issue by farunurisonmez** [farunurisonmez/client-app-osrm#9]
Bu GitHub eylemi (GitHub Actions), bir belirli şartın sağlandığı (push işlemi ve "gh-app" dalı) zaman belirli bir işlemi gerçekleştiren otomasyonlu bir işlemi temsil eder. Ayrıca, bu işlem bir "workflow" (çalışma akışı) olarak adlandırılır.

Bu işlem, belirli bir GitHub deposundaki bir olayı (push işlemi "gh-app" dalına) tetiklediğinde gerçekleşir. İşte bu işlemin adımları:

Checkout (Çıkarma):
Açıklama: Bu adımda, ilgili depoyu (repository) klonlar ve belirli bir dalı (branch) işlemek üzere ayarlar. Bu, mevcut kodun son durumunu elde etmek için kullanılır.
İsim: Checkout
Install and Build (Yükle ve Derle):
Açıklama: Bu adımda, projenin bağımlılıklarını (dependencies) yüklemek için npm kullanılır ve ardından projeyi derler. Bu adım, projenin son kullanıma hazır hale getirilmesine yardımcı olur.
İsim: Install and Build
Deploy (Yayınlama):
Açıklama: Bu adımda, GitHub Sayfaları'na projenin derlenmiş sürümünü dağıtır. Deploy işlemi için "JamesIves/github-pages-deploy-action" adlı eylemi kullanır.
İsim: Deploy
Parametreler:
branch: GitHub Sayfaları'nda yayımlanacak dalı belirtir (genellikle "gh-pages").
folder: Sayfalara yüklenecek dosyaların bulunduğu klasörü belirtir (genellikle "build").
Bu işlem, GitHub deposundaki belirli bir dal üzerine yapılan güncellemeleri işleyerek, bu güncellemelerin sonucunda derlenen projenin GitHub Sayfaları'na (GitHub Pages) dağıtılmasını otomatikleştirir. Bu, web projelerini hızlı ve otomatik olarak yayınlamak için kullanışlıdır.

GitHub Actions'ın kullanımı, yazılım geliştirme süreçlerini otomatikleştirme ve iyileştirme açısından büyük bir avantaj sağlar. Bu işlem, özellikle GitHub Sayfaları gibi GitHub tarafından sağlanan hizmetlerle kullanıldığında projelerin kolayca yayınlanmasını sağlar.

**Comment by 0xfaru** [comment]
[Warning] [blocked] The page at https://farunurisonmez.github.io/client-app-osrm/ was not allowed to display insecure content from http://router.project-osrm.org/route/v1/driving/35.5546374,38.6582232;37.1012388,39.4191717?overview=false&alternatives=false&steps=true. (main.11cd25e9.js, line 2)

[Error] Not allowed to request resource
	(anonymous function) (main.11cd25e9.js:2:323477)
	Promise
	(anonymous function) (main.11cd25e9.js:2:320681)
	Bt (main.11cd25e9.js:2:324679)
	value (main.11cd25e9.js:2:328359)
	(anonymous function) (main.11cd25e9.js:2:332129)
	f (main.11cd25e9.js:2:294538)
	(anonymous function) (main.11cd25e9.js:2:295881)
	u (main.11cd25e9.js:2:300449)
	a (main.11cd25e9.js:2:332462)
	(anonymous function) (main.11cd25e9.js:2:332521)
	Promise
	(anonymous function) (main.11cd25e9.js:2:332412)
	(anonymous function) (main.11cd25e9.js:2:332668)
	rl (main.11cd25e9.js:2:242874)
	ku (main.11cd25e9.js:2:263102)
	(anonymous function) (main.11cd25e9.js:2:259692)
	x (main.11cd25e9.js:2:287662)
	z (main.11cd25e9.js:2:288196)
[Error] XMLHttpRequest cannot load http://router.project-osrm.org/route/v1/driving/35.5546374,38.6582232;37.1012388,39.4191717?overview=false&alternatives=false&steps=true due to access control checks.
	(anonymous function) (main.11cd25e9.js:2:323477)
	Promise
	(anonymous function) (main.11cd25e9.js:2:320681)
	Bt (main.11cd25e9.js:2:324679)
	value (main.11cd25e9.js:2:328359)
	(anonymous function) (main.11cd25e9.js:2:332129)
	f (main.11cd25e9.js:2:294538)
	(anonymous function) (main.11cd25e9.js:2:295881)
	u (main.11cd25e9.js:2:300449)
	a (main.11cd25e9.js:2:332462)
	(anonymous function) (main.11cd25e9.js:2:332521)
	Promise
	(anonymous function) (main.11cd25e9.js:2:332412)
	(anonymous function) (main.11cd25e9.js:2:332668)
	rl (main.11cd25e9.js:2:242874)
	ku (main.11cd25e9.js:2:263102)
	(anonymous function) (main.11cd25e9.js:2:259692)
	x (main.11cd25e9.js:2:287662)
	z (main.11cd25e9.js:2:288196)
[Error] Unhandled Promise Rejection: AxiosError: Network Error

**Comment by 0xfaru** [comment]
Sayfa yayında.
